version: '3.1'

services:
  db:
    image: postgres:12.9-alpine

    # For debugging purposes
    command: ["postgres", "-c", "log_statement=all"]

    restart: always

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
